// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type DeptCountRequest struct {
	Dept string `form:"dept"`
}

type DeptCountResponse struct {
	Dept  string `json:"dept"`
	Count int    `json:"count"`
}

type Request struct {
	Name string `path:"name"`
}

type Response struct {
	Message string `json:"message"`
}
