// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"helloapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/dept/count",
				Handler: getDeptCountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/hello/:name",
				Handler: HelloapiHandler(serverCtx),
			},
		},
	)
}
